# fly.toml app configuration file generated for nc-be-project on 2025-05-04T14:20:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nc-be-project'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
